-- Run this in the active Supabase project's SQL Editor.
-- It creates an application-facing user directory and an activity ledger.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text,
  full_name text,
  phone text,
  role text not null default 'user',
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  actor_role text,
  action text not null,
  entity_type text,
  entity_id text,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_actor_id_idx on public.activity_logs(actor_id);
create index if not exists activity_logs_action_idx on public.activity_logs(action);

alter table public.profiles enable row level security;
alter table public.activity_logs enable row level security;

create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    'user'
  );
$$;

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile"
on public.profiles for select to authenticated
using (id = auth.uid() or public.current_app_role() = 'admin');

drop policy if exists "Admins read activity logs" on public.activity_logs;
create policy "Admins read activity logs"
on public.activity_logs for select to authenticated
using (public.current_app_role() = 'admin');

create or replace function public.sync_auth_user_profile()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (
    id, email, username, full_name, phone, role, last_sign_in_at, created_at, updated_at
  )
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'username',
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'username'),
    coalesce(new.phone, new.raw_user_meta_data ->> 'phone'),
    coalesce(new.raw_app_meta_data ->> 'role', new.raw_user_meta_data ->> 'role', 'user'),
    new.last_sign_in_at,
    new.created_at,
    now()
  )
  on conflict (id) do update set
    email = excluded.email,
    username = excluded.username,
    full_name = excluded.full_name,
    phone = excluded.phone,
    role = excluded.role,
    last_sign_in_at = excluded.last_sign_in_at,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists sync_auth_user_profile_trigger on auth.users;
create trigger sync_auth_user_profile_trigger
after insert or update on auth.users
for each row execute procedure public.sync_auth_user_profile();

insert into public.profiles (
  id, email, username, full_name, phone, role, last_sign_in_at, created_at, updated_at
)
select
  id,
  email,
  raw_user_meta_data ->> 'username',
  coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'username'),
  coalesce(phone, raw_user_meta_data ->> 'phone'),
  coalesce(raw_app_meta_data ->> 'role', raw_user_meta_data ->> 'role', 'user'),
  last_sign_in_at,
  created_at,
  now()
from auth.users
on conflict (id) do update set
  email = excluded.email,
  username = excluded.username,
  full_name = excluded.full_name,
  phone = excluded.phone,
  role = excluded.role,
  last_sign_in_at = excluded.last_sign_in_at,
  updated_at = now();

create or replace function public.log_recruitment_change()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  row_id text;
  action_name text;
  actor_role_value text;
begin
  row_id := coalesce(to_jsonb(new) ->> 'id', to_jsonb(old) ->> 'id');
  action_name := lower(tg_table_name) || '_' || lower(tg_op);
  actor_role_value := coalesce(
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    'system'
  );

  insert into public.activity_logs (
    actor_id, actor_email, actor_role, action, entity_type, entity_id, description, metadata
  )
  values (
    auth.uid(),
    auth.jwt() ->> 'email',
    actor_role_value,
    action_name,
    tg_table_name,
    row_id,
    initcap(tg_op) || ' activity on ' || tg_table_name,
    jsonb_build_object(
      'status', coalesce(to_jsonb(new) ->> 'status', to_jsonb(old) ->> 'status')
    )
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists audit_applications_changes on public.applications;
create trigger audit_applications_changes
after insert or update or delete on public.applications
for each row execute procedure public.log_recruitment_change();

drop trigger if exists audit_jobs_changes on public.jobs;
create trigger audit_jobs_changes
after insert or update or delete on public.jobs
for each row execute procedure public.log_recruitment_change();
