create table if not exists public.interview_panel_scores (
  id bigint generated by default as identity primary key,
  application_id text not null,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  reviewer_email text,
  reviewer_role text not null check (reviewer_role in ('hr', 'registrar', 'admin')),
  communication smallint not null check (communication between 0 and 25),
  role_knowledge smallint not null check (role_knowledge between 0 and 25),
  experience smallint not null check (experience between 0 and 25),
  culture_fit smallint not null check (culture_fit between 0 and 25),
  total_score smallint not null check (total_score between 0 and 100),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (application_id, reviewer_id)
);

create index if not exists interview_panel_scores_application_idx
  on public.interview_panel_scores (application_id);

alter table public.interview_panel_scores enable row level security;

drop policy if exists "Panel members can view interview scores" on public.interview_panel_scores;
create policy "Panel members can view interview scores"
on public.interview_panel_scores for select
to authenticated
using (
  coalesce(auth.jwt() -> 'user_metadata' ->> 'role', '') in ('hr', 'registrar', 'admin')
);

drop policy if exists "Reviewers can manage their scores" on public.interview_panel_scores;
create policy "Reviewers can manage their scores"
on public.interview_panel_scores for all
to authenticated
using (reviewer_id = auth.uid())
with check (
  reviewer_id = auth.uid()
  and coalesce(auth.jwt() -> 'user_metadata' ->> 'role', '') in ('hr', 'registrar', 'admin')
);

notify pgrst, 'reload schema';
