-- Run once in the active Supabase project's SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    'user'
  );
$$;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  actor_role text,
  action text not null,
  entity_type text,
  entity_id text,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_entity_idx on public.activity_logs(entity_type, entity_id);

create or replace function public.log_recruitment_change()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  row_id text;
begin
  row_id := coalesce(to_jsonb(new) ->> 'id', to_jsonb(old) ->> 'id');
  insert into public.activity_logs (
    actor_id, actor_email, actor_role, action, entity_type, entity_id, description, metadata
  ) values (
    auth.uid(),
    auth.jwt() ->> 'email',
    public.current_app_role(),
    lower(tg_table_name) || '_' || lower(tg_op),
    tg_table_name,
    row_id,
    initcap(tg_op) || ' activity on ' || tg_table_name,
    jsonb_build_object('status', coalesce(to_jsonb(new) ->> 'status', to_jsonb(old) ->> 'status'))
  );
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists audit_applications_changes on public.applications;
create trigger audit_applications_changes
after insert or update or delete on public.applications
for each row execute procedure public.log_recruitment_change();

drop trigger if exists audit_jobs_changes on public.jobs;
create trigger audit_jobs_changes
after insert or update or delete on public.jobs
for each row execute procedure public.log_recruitment_change();

create table if not exists public.email_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null check (category in ('reference', 'interview', 'rejection', 'offer', 'reminder', 'onboarding', 'general')),
  subject text not null,
  body text not null,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reference_requests (
  id uuid primary key default gen_random_uuid(),
  application_id text not null,
  referee_name text not null,
  referee_email text not null,
  relationship text,
  token uuid not null unique default gen_random_uuid(),
  status text not null default 'Pending' check (status in ('Pending', 'Completed', 'Expired', 'Cancelled')),
  due_at timestamptz,
  sent_at timestamptz,
  last_reminder_at timestamptz,
  reminders_sent smallint not null default 0,
  completed_at timestamptz,
  response jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reminder_deliveries (
  id bigint generated by default as identity primary key,
  reminder_key text not null unique,
  reminder_type text not null,
  application_id text,
  reference_request_id uuid references public.reference_requests(id) on delete cascade,
  recipient text not null,
  sent_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists reference_requests_application_idx on public.reference_requests(application_id);
create index if not exists reference_requests_status_due_idx on public.reference_requests(status, due_at);
create index if not exists email_templates_category_idx on public.email_templates(category, is_active);

alter table public.email_templates enable row level security;
alter table public.reference_requests enable row level security;
alter table public.reminder_deliveries enable row level security;

drop policy if exists "Recruitment managers read templates" on public.email_templates;
create policy "Recruitment managers read templates"
on public.email_templates for select to authenticated
using (public.current_app_role() in ('hr', 'admin'));

drop policy if exists "Recruitment managers manage templates" on public.email_templates;
create policy "Recruitment managers manage templates"
on public.email_templates for all to authenticated
using (public.current_app_role() in ('hr', 'admin'))
with check (public.current_app_role() in ('hr', 'admin'));

drop policy if exists "Recruitment managers read references" on public.reference_requests;
create policy "Recruitment managers read references"
on public.reference_requests for select to authenticated
using (public.current_app_role() in ('hr', 'admin'));

drop policy if exists "Recruitment managers manage references" on public.reference_requests;
create policy "Recruitment managers manage references"
on public.reference_requests for all to authenticated
using (public.current_app_role() in ('hr', 'admin'))
with check (public.current_app_role() in ('hr', 'admin'));

drop policy if exists "Recruitment managers read reminders" on public.reminder_deliveries;
create policy "Recruitment managers read reminders"
on public.reminder_deliveries for select to authenticated
using (public.current_app_role() in ('hr', 'admin'));

insert into public.email_templates (name, category, subject, body)
select *
from (values
  (
    'Reference request',
    'reference',
    'Reference request for {{candidate_name}}',
    'Hello {{referee_name}},\n\n{{candidate_name}} has listed you as a referee for the position of {{job_title}} at Pentecost University. Please complete the secure reference form by {{due_date}}:\n\n{{reference_link}}\n\nHuman Resources Department'
  ),
  (
    'Interview reminder',
    'reminder',
    'Interview reminder: {{job_title}}',
    'Hello {{candidate_name}},\n\nThis is a reminder that your interview for {{job_title}} is scheduled for {{interview_time}}.\n\nMeeting link: {{meeting_link}}\n\nPentecost University HR'
  ),
  (
    'Missing documents reminder',
    'onboarding',
    'Onboarding documents required',
    'Hello {{candidate_name}},\n\nYour onboarding record still has documents awaiting upload or approval. Please sign in to the recruitment portal to review the outstanding requirements.\n\nPentecost University HR'
  )
) as defaults(name, category, subject, body)
where not exists (
  select 1 from public.email_templates existing where existing.name = defaults.name
);

notify pgrst, 'reload schema';
